### ISSUE TITLE
Can read2tree be run offline and with custom marker gene list? 

### ISSUE THREAD

**Issue by masudermann** [DessimozLab/read2tree#22]
Hello, 

I tried out read2tree and was impressed. I had a quick followup. Is it possible for users to input their own custom list of maker genes? 

I work with several different _Phytophthora_ species. When I use the OMA browser, I can only obtain marker genes from 7 species. Being able to provide my own set of genes would be advantageous.

From my quick look at the paper, documentation, and other questions people had, it looks like there isn't currently a way to run read2tree offline or with a custom set of marker genes. If this is is the case, will a future update incorporate this option?

**Comment by alpae** [comment]
Dear @masudermann 

it is possible, but not entirely straight forward. You need to provide 

1. a list of marker genes in fasta format for their protein sequence. Note that it is expected that each sequence contains the species it belongs encoded in a `[species tag]` at the end of the fasta header. There must be at most one sequence per species in each marker gene (and the sequence need to be all orthologous to one another).
2. You need to have a fast file with the same headers containing all the coding sequences (CDS) coresponding to the protein sequences. You can provide all the sequences in a single fasta file.

Then, you should be able to run read2tree with the command:

    read2tree --tree --standalone_path <marker_genes>  --dna_reference <cds_file> ...

If you observe any problems we would be glad to hear about them. The tool should definitively be able to work also with markers not coming from OMA (but it is certainly much less tested).

Cheers Adrian

**Comment by masudermann** [comment]
Thank you! The instructions are helpful. I will keep you posted.

**Comment by Lijiaxuan420** [comment]
Hello, I try to use my own pep and cds files (prepared according to your requirements) to run read2tree, but it gave me error with：

(r2t) [ljx@Centos-30013 read2tree]$ /home/ljx/tools/read2tree/build/scripts-3.10/read2tree --threads 40 --standalone_path /data/share_data/ljx-30013/read2tree/pep --dna_reference /data/share_data/ljx-30013/read2tree/cds.fasta --reads /data/share_data/ljx-30013/read2tree/CHS110_2x_R1.fq /data/share_data/ljx-30013/read2tree/CHS110_2x_R2.fq --output_path 8429_cds_snake_110_2x

--- Load OGs with min 0 species from oma /data/share_data/ljx-30013/read2tree/pep - mode = marker_genes ---
Loading files for pre-filter: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 8429/8429 [00:00<00:00, 16721.89 OGs/s]
2023-05-11 17:47:45,262 - read2tree.OGSet - INFO - --- Load ogs and find their corresponding DNA seq from /data/share_data/ljx-30013/read2tree/cds.fasta ---
2023-05-11 17:47:45,263 - read2tree.OGSet - INFO - Loading cds.fasta into memory. This might take a while . . . 
Loading OGs:   0%|                                                                                                                                     | 0/8429 [00:02<?, ? OGs/s]
Traceback (most recent call last):
  File "/home/ljx/tools/read2tree/build/scripts-3.10/read2tree", line 16, in <module>
    main(sys.argv[1:], exe_name=exe_name(), desc=desc)
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/main.py", line 289, in main
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/OGSet.py", line 79, in __init__
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/OGSet.py", line 186, in _load_ogs
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/OGSet.py", line 361, in _get_dna_records
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/OGSet.py", line 322, in _get_dna_from_fasta
  File "/home/ljx/miniconda3/envs/r2t/lib/python3.10/site-packages/read2tree-0.1.5-py3.10.egg/read2tree/OGSet.py", line 282, in _get_dna_from_REST
KeyError: 'cdna'

Can you please help me with this issue?

Thanks,
Jiaxuan Li

**Comment by sci-study** [comment]
I'm currently attempting the same strategy. I've collected 69 OMA groups composed of 22 genomes. I've also made a fasta file with the corresponding CDS sequences whilst using the same headers found in the oma groups. However, I'm encountering issues that I'm finding hard to overcome. 

i.e (Marker gene)
>Protein 1 [Animal 1]
DVAEKCRVL
>Protein 1 [Animal 2] 
DVAEKCRVL

(Corresponding CDS file)
>Protein 1 [Animal 1]
ATCGATCGATCG
>Protein 1 [Animal 2] 
ATCGATCGATCG

However, when i start the Read2Tree program with your suggested command (Minus --tree, I'm using multi-sepcies mode)

read2tree --standalone_path <path_to_markers>  --dna_reference <path_to_corresponding_cds>

I get the error:

--- Load OGs with min 0 species from oma /home/youseuf/post_doc/praveena_chigger/oma/acriforme_protein_dataset/Output/test_markers - mode = marker_genes ---
Loading files for pre-filter: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 69/69 [00:00<00:00, 1443.47 OGs/s]
2023-07-12 15:01:56,283 - read2tree.OGSet - INFO - --- Load ogs and find their corresponding DNA seq from /home/youseuf/post_doc/praveena_chigger/oma/acriforme_protein_dataset/Output/reference_data/total_orths_cds.fasta ---
2023-07-12 15:01:56,283 - read2tree.OGSet - INFO - Loading total_orths_cds.fasta into memory. This might take a while . . . 
Loading OGs:   0%|                                                                                                                                                         | 0/69 [00:00<?, ? OGs/s]
Loading OGs:   0%|                                                                                                                                                         | 0/69 [06:01<?, ? OGs/s]
Traceback (most recent call last):
  File "/home/youseuf/miniconda3/envs/read2tree2/bin/read2tree", line 4, in <module>
    __import__('pkg_resources').run_script('read2tree==0.1.4', 'read2tree')
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1570, in run_script
    exec(script_code, namespace, namespace)
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/EGG-INFO/scripts/read2tree", line 16, in <module>
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/read2tree/main.py", line 289, in main
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/read2tree/OGSet.py", line 79, in __init__
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/read2tree/OGSet.py", line 192, in _load_ogs
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/read2tree/OGSet.py", line 337, in _check_dna_aa_length_consistency
  File "/home/youseuf/miniconda3/envs/read2tree2/lib/python3.8/site-packages/read2tree-0.1.4-py3.8.egg/read2tree/OGSet.py", line 337, in <dictcomp>
AttributeError: 'NoneType' object has no attribute 'id'

when I look into the mplog.log file i see: 

2023-07-12 15:01:56,308 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): omabrowser.org:80
2023-07-12 15:01:56,474 - urllib3.connectionpool - DEBUG - http://omabrowser.org:80 "GET /api/protein/XP/ HTTP/1.1" 301 162
2023-07-12 15:01:56,476 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): omabrowser.org:443
2023-07-12 15:02:56,622 - urllib3.connectionpool - DEBUG - https://omabrowser.org:443 "GET /api/protein/XP/ HTTP/1.1" 504 160
2023-07-12 15:02:56,625 - read2tree.OGSet - DEBUG - DNA not found for XP_046914939.1_OG24421.

Any help would be extremely appreciated.

**Comment by sinamajidian** [comment]
For future references:  we have also some instruction [here](https://github.com/DessimozLab/read2tree/wiki/obtaining-marker-genes-for-viral-dataset) which works for NCBI refSeq.  We would be happy to generalise it for specific format of your interest.
