### ISSUE TITLE
cannot get dna from REST

### ISSUE THREAD

**Issue by GYQ-form** [DessimozLab/read2tree#41]
Hello and thank you first for your interesting work.

When I followed the step-by-step [tutorial](https://github.com/dvdylus/read2tree_paper/tree/main/corona) for analysing the corona virus dataset, I met a problem when conduct this step:

```bash
> read2tree --reference --standalone ../marker_genes/ --dna_reference ../viruses.cdna.fa.gz
--- Load OGs with min 0 species from oma ../marker_genes - mode = marker_genes ---                                                                                                                                   
Loading files for pre-filter: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1593.05 OGs/s]
2023-09-06 05:00:23,023 - read2tree.OGSet - INFO - --- Load ogs and find their corresponding DNA seq from ../viruses.cdna.fa.gz ---
2023-09-06 05:00:23,024 - read2tree.OGSet - INFO - Loading viruses.cdna.fa.gz into memory. This might take a while . . . 
Loading OGs:   0%|                                                                                                                                                                           | 0/8 [00:07<?, ? OGs/s]
Traceback (most recent call last):                                                                        
  File "/home/gurc/mambaforge/envs/evolution/bin/read2tree", line 16, in <module>                                                                                                                                    
    main(sys.argv[1:], exe_name=exe_name(), desc=desc)
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/main.py", line 289, in main
    ogset = OGSet(args, oma_output=oma_output, progress=progress)  # Generate the OGs with their DNA sequences
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/OGSet.py", line 79, in __init__
    self.ogs = self._load_ogs()
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/OGSet.py", line 186, in _load_ogs
    ogs[name].dna = self._get_dna_records(ogs[name].aa,
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/OGSet.py", line 361, in _get_dna_records
    og_cdna.append(self._get_dna_from_fasta(record, db))
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/OGSet.py", line 322, in _get_dna_from_fasta
    return self._get_dna_from_REST(record)
  File "/home/gurc/mambaforge/envs/evolution/lib/python3.10/site-packages/read2tree/OGSet.py", line 282, in _get_dna_from_REST
    seq = oma_record.json()['cdna']
KeyError: 'cdna'
```

It is quite confusing since I totally followed the instructions in the [tutorial](https://github.com/dvdylus/read2tree_paper/tree/main/corona) when exporting marker genes. I tried to use the backend API directly on the browser, but still got the same 404 response (e.g. X005000001) :
![image](https://github.com/DessimozLab/read2tree/assets/79566479/7cb56681-0d9f-49bc-aba0-c8aa00fc5cee)

The OMA database is supposed to contain coronavirus species data since you have already run reed2tree on this data.  I can't figure out what went wrong.

Any help would be greatly appreciated.

Best regards,
Yuqiao Gong

**Comment by sinamajidian** [comment]
Hi 
Thanks for using read2tree.
With `--dna_reference`, read2tree shouldn't use the restAPI. Are you sure all the protein record in gene_marker folder appeared in `viruses.cdna.fa`?

Btw, for corona analysis we used specific instance of oma:  https://corona.omabrowser.org/oma/home/

**Comment by GYQ-form** [comment]
There is indeed a problem with my `viruses.cdna.fa` file. The problem has been fixed, thanks a lot~
