### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by pengyan19** [DessimozLab/read2tree#60]
Hi, when i used the read2tree, i meet a question as follows:

Re-loading files: 5997 OGs [02:42, 36.81 OGs/s]
Re-loading references for mapping from folder: 100%|?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 5/5 [00:00<00:00,  7.16 species/s]
Loading alignments : 0 Alignment [00:00, ? Alignment/s]
Mapping reads to species:   0%|          | 0/5 [00:00<?, ? species/s]/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/subprocess.py:966: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
No match found for '[MAIN] Done (', found '['  (at char 0), (line:1, col:1)
Mapping reads to species:   0%|          | 0/5 [00:00<?, ? species/s]
Traceback (most recent call last):
  File "/public/home/pengyan/biosoft/read2tree/read2tree/bin/read2tree", line 16, in <module>
    main(sys.argv[1:], exe_name=exe_name(), desc=desc)
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/main.py", line 357, in main
    mapper = Mapper(args, og_set=ogset.ogs, ref_set=reference.ref, progress=progress)  # Run the mapping
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/Mapper.py", line 80, in __init__
    self._map_reads_to_references(ref_set)
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/Mapper.py", line 289, in _map_reads_to_references
    processed_reads = self._call_wrapper(ref_tmp_file_handle, reads,
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/Mapper.py", line 110, in _call_wrapper
    ngm = ngm_wrapper()
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/wrappers/read_mappers/ngm.py", line 62, in __call__
    self.result = self._read_result(error, self.ref_input, self.tmp_folder)
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/wrappers/read_mappers/ngm.py", line 117, in _read_result
    result = parser.to_dict(outfile, output)
  File "/public/home/pengyan/anaconda3/envs/r2t/lib/python3.10/site-packages/read2tree/wrappers/read_mappers/parser.py", line 43, in to_dict
    reads_mapped, total_reads, mapping_time = self.parse(stdout)
TypeError: cannot unpack non-iterable NoneType object

**Comment by sinamajidian** [comment]
Hello
It would be great if you could share with us a few things:  the command line you ran, how you generated marker genes, the mplog.log file and the output log on screen when you ran read2tree.

I think you ran it a few times, which makes it difficult to debug. Read2tree tries to resume previous runs using log and output folder. 
Please start over in a empty folder if it doesnt take too much resource.

**Comment by pengyan19** [comment]
Hi, this is the code
python /public/home/pengyan/biosoft/read2tree/read2tree/bin/read2tree --standalone_path marker_genes/ --output_path /public/home/pengyan/biosoft/read2tree --reference --dna_reference dna_ref.fa

**Comment by hansenwang123** [comment]
> Hi, this is the code python /public/home/pengyan/biosoft/read2tree/read2tree/bin/read2tree --standalone_path marker_genes/ --output_path /public/home/pengyan/biosoft/read2tree --reference --dna_reference dna_ref.fa

Hi, I confronted the same error, I would like to know if you find the solution for this?
