### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ppat818** [DessimozLab/read2tree#62]
Hi, 

 I installed read2tree using Bioconda. I tried running the first command for multiple species mode but I get the following error immediately:

Traceback (most recent call last):
```
  File "/home/ppat818/anaconda3/envs/env-read2tree/bin/read2tree", line 16, in <module>
    main(sys.argv[1:], exe_name=exe_name(), desc=desc)
  File "/home/ppat818/anaconda3/envs/env-read2tree/lib/python3.10/site-packages/read2tree/main.py", line 287, in main
    oma_output = OMAOutputParser(args)
  File "/home/ppat818/anaconda3/envs/env-read2tree/lib/python3.10/site-packages/read2tree/parser/OMAOutputParser.py", line 22, in __init__
    self.oma_output_path = self._check_oma_output_path()
  File "/home/ppat818/anaconda3/envs/env-read2tree/lib/python3.10/site-packages/read2tree/parser/OMAOutputParser.py", line 59, in _check_oma_output_path
    elif standalone_path.parts[-1] == OMA_MARKER_GENE_EXPORT:
IndexError: tuple index out of range
```

An mplog.log file is created but it is empty. I have updated Conda and am using the latest versions of all dependencies. 

I appreciate any help :)

**Comment by sinamajidian** [comment]
Hello, 

I would suggest first running read2tree on the test dataset provided on github, and tell us whether you get the tree.
Could you please tell us the command line you are using to run read2tree? 
Please also describe the input files and how you get the gene markers. 

Best,
Sina

**Comment by alpae** [comment]
Closing this issue. In case the problem persists, feel free to reopen it
